apiVersion: v1
kind: Service
metadata:
  name: jiaozifs-docs-service
  labels:
    apptype: jiaozifs-docs
spec:
  type: ClusterIP
  selector:
    app: jiaozifs-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80