apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docs-gitdata-ai-certificate
spec:
  secretName: docs-gitdata-ai-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - docs.gitdata.ai
